// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNmqCh_y0liCGXvzCtfTRIfiLKtbFGb8g',
    appId: '1:1000784057775:web:bb6877fc830d2dc4230b5a',
    messagingSenderId: '1000784057775',
    projectId: 'final-year-project-53d36',
    authDomain: 'final-year-project-53d36.firebaseapp.com',
    storageBucket: 'final-year-project-53d36.appspot.com',
    measurementId: 'G-F53T0LDSV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEdQE6zTzw_oTpoISi3xOOyluwDtnkSAk',
    appId: '1:1000784057775:android:f5fed5999c601509230b5a',
    messagingSenderId: '1000784057775',
    projectId: 'final-year-project-53d36',
    storageBucket: 'final-year-project-53d36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlcayj45M7Y3MkXTn9_JUc0cg_Q06CBVg',
    appId: '1:1000784057775:ios:475b2c684814cb88230b5a',
    messagingSenderId: '1000784057775',
    projectId: 'final-year-project-53d36',
    storageBucket: 'final-year-project-53d36.appspot.com',
    iosClientId: '1000784057775-4fkn3lbc7clp8q7vekfhp5nplhfulhua.apps.googleusercontent.com',
    iosBundleId: 'com.example.testsy',
  );
}
